install.packages("mongolite",   repos = "https://cloud.r-project.org/", dependencies = TRUE)
install.packages("tidyverse",   repos = "https://cloud.r-project.org/", dependencies = TRUE)
install.packages("data.table",  repos = "https://cloud.r-project.org/", dependencies = TRUE)
install.packages("broom",       repos = "https://cloud.r-project.org/", dependencies = TRUE)
install.packages("streamR",     repos = "https://cloud.r-project.org/", dependencies = TRUE)
install.packages("rtweet",      repos = "https://cloud.r-project.org/", dependencies = TRUE)
install.packages("httpuv",      repos = "https://cloud.r-project.org/", dependencies = TRUE)
install.packages("jsonlite",    repos = "https://cloud.r-project.org/", dependencies = TRUE)
